# Problem Statement:
Predicting Survival in the Titanic Data Set We will be using a decision tree to make predictions about the Titanic data set from Kaggle. This data set provides information on the Titanic passengers and can be used to predict whether a passenger survived or not. 


In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sb 
import matplotlib.pyplot as plt 
import sklearn 
from pandas import Series, DataFrame 
from pylab import rcParams 
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
Url= 'https://raw.githubusercontent.com/Nexosis/sampledata/master/titanic-train.csv'
#titanic = pd.read_csv('/content/titanic-train.csv')
titanic = pd.read_csv(Url)


In [3]:
titanic.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [5]:
titanic.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Embarked    889 non-null object
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [7]:
titanic.Age.fillna(titanic.Age.mean(),inplace=True)

In [8]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Embarked    889 non-null object
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [9]:
titanic.Embarked.fillna(method='ffill',inplace=True)

In [10]:
titanic.head()

Survived  Pclass Embarked     Sex   Age  SibSp  Parch     Fare
0         0       3        S    male  22.0      1      0   7.2500
1         1       1        C  female  38.0      1      0  71.2833
2         1       3        S  female  26.0      0      0   7.9250
3         1       1        S  female  35.0      1      0  53.1000
4         0       3        S    male  35.0      0      0   8.0500

In [11]:
titanic.Sex.replace(['female','male'],[0,1],inplace=True)

In [12]:
titanic = pd.get_dummies(titanic, columns=['Embarked'])

In [13]:
titanic.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    1  22.0      1      0   7.2500           0           0   
1         1       1    0  38.0      1      0  71.2833           1           0   
2         1       3    0  26.0      0      0   7.9250           0           0   
3         1       1    0  35.0      1      0  53.1000           0           0   
4         0       3    1  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [14]:
y=titanic.Survived
X=titanic.drop(columns='Survived')

In [15]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0       3    1  22.0      1      0   7.2500           0           0   
1       1    0  38.0      1      0  71.2833           1           0   
2       3    0  26.0      0      0   7.9250           0           0   
3       1    0  35.0      1      0  53.1000           0           0   
4       3    1  35.0      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [16]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [32]:
DT=DecisionTreeClassifier()

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

In [34]:
model=DT.fit(X_train,y_train)

In [35]:
y_pred=model.predict(X_test)

In [36]:
confusion_matrix(y_test,y_pred)

array([[136,  24],
       [ 32,  76]], dtype=int64)

In [37]:
accuracy_score(y_test,y_pred)

0.7910447761194029

In [38]:
model.feature_importances_

array([0.10218977, 0.32107882, 0.23741507, 0.05373537, 0.02399979,
       0.23986536, 0.00796058, 0.        , 0.01375524])

In [39]:
X.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [40]:
X_imp=X[['Pclass', 'Sex', 'Age', 'Fare']]

In [41]:
X_imp.columns

Index(['Pclass', 'Sex', 'Age', 'Fare'], dtype='object')

In [42]:
X_imp_train, X_imp_test, y_train, y_test = train_test_split(X_imp, y, test_size=0.30, random_state=30)

In [43]:
model_imp=DT.fit(X_imp_train,y_train)

In [44]:
y_pred=model_imp.predict(X_imp_test)

In [45]:
confusion_matrix(y_test,y_pred)

array([[131,  29],
       [ 34,  74]], dtype=int64)

In [46]:
accuracy_score(y_test,y_pred)

0.7649253731343284